# Generated by Django 4.0.5 on 2022-07-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0002_cliente_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_empleado', models.CharField(max_length=50)),
                ('ape_empleado', models.CharField(max_length=50)),
                ('mail_empleado', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='articulo',
        ),
    ]
