# Generated by Django 4.0.5 on 2022-07-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_empleado_delete_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='mail_cliente',
            new_name='mail_proveedor',
        ),
    ]
