# Generated by Django 4.0.5 on 2022-07-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0004_rename_mail_cliente_proveedor_mail_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ape_cliente',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='mail_cliente',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nom_cliente',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='ape_empleado',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='mail_empleado',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nom_empleado',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='mail_proveedor',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nom_proveedor',
            new_name='nombre',
        ),
    ]
